import { Injectable } from '@nestjs/common';
import { SupabaseService } from '../supabase/supabase.service';

@Injectable()
export class ExportService {
  constructor(private supabase: SupabaseService) {}

  async exportMarkdown(canvasId: string): Promise<{ content: string; filename: string }> {
    const { data: canvas } = await this.supabase.admin
      .from('canvases')
      .select('*, nodes(*)')
      .eq('id', canvasId)
      .single();

    if (!canvas) throw new Error('Canvas not found');

    let md = `# ${canvas.title}\n\n`;
    md += `> Generated by MindCanvas on ${new Date().toLocaleDateString()}\n\n`;

    for (const node of canvas.nodes || []) {
      md += `## ${node.title}\n\n`;
      md += `${node.content || ''}\n\n---\n\n`;
    }

    return {
      content: md,
      filename: `${canvas.title.replace(/\s+/g, '-').toLowerCase()}.md`,
    };
  }

  async exportJson(canvasId: string): Promise<any> {
    const { data: canvas } = await this.supabase.admin
      .from('canvases')
      .select('*, nodes(*), connections(*)')
      .eq('id', canvasId)
      .single();

    return canvas;
  }
}
